### ISSUE TITLE
Set-up and parameters to tune FaIR for AR6-like runs

### ISSUE THREAD

**Issue by fracamil** [OMS-NetZero/FAIR#106]
Dear Chris,

You recently created a new version of FaIR able to load SSPs (v1.6.4). You mentionned in an answer of the associated issue thread that "the default FaIR setup is for an AR5-like run. The aerosol and ozone assessments have changed substantially and the historical GHGs will require new "natural" balancing emissions. So yes, SSPs can be implemented, but with the caveat that results may not match either reality or the AR6 assessments in their default setups.".

I looked at the provided examples (https://github.com/chrisroadmap/ar6/tree/main/notebooks) and read AR6 WG1 SM7. This was really useful. Here is what I understood to perform AR6-like runs (sorry if I don't use the correct vocabulary, I am a beginner in running climate models...):
- Use the new balanced natural emissions, the solar and volcanic forcing files (with an adaptation for solar forcing?).
- Use the geoffroy function,
- Use the Meinshausen function for GHG,
- Use the thornhill-skeie function to calculate ozone ERF,
- Use the constrained ensemble values (median values for non probabilistic runs) for parameters (ECS, TCR, etc). 

I was not able to retrieve the constrained ensemble values for the parameters. It's impossible for me to rerun the different steps (and the 1 million cases), as I do not have access to a multiprocessor server and have to run FaIR on my computer.

In order to be able to run FaIR in AR6 "mode", would it be possible to have access to a file containing the constrained ensemble median values for the different parameters to use? Having access to a file containing all the constrained parameters to use (2237 possibilities if I read correctly) would be even better in order to be able to draw the 5-95% intervals of the obtained results... 

The aim is to be able to perform these calculations in order to model the effect of different scenarios of aviation emissions and non-CO2 effects mitigation on the total ERF and GSAT. I perfectly understand that my request could be perceived as naïve or too complicated to answer (maybe the data are "secret", too). Anyway, I thank you in advance for your help.

**Comment by chrisroadmap** [comment]
Hello @fracamil, 

Nothing here is secret and it's all on my AR6 repository - it's just that going from the default setup of FaIR to the one used in AR6 took several months and about 40 different keywords specified to the `fair_scm` interface ;)

One simple solution would be to add a new keyword to `fair_scm` (another one!) that would automatically select the AR6 median calibration. Anything beyond that probably doesn't belong in the main FaIR code base, as we're getting into calibrations rather than code changes.

I just noticed that my constrained 2237 member AR6 calibration isn't publicly available. Let's fix that first. 

https://github.com/chrisroadmap/ar6/issues/19

After this, you might be able to run the AR6 calibration. The multiprocessing is just used to speed things up, it should run fine in serial. I'll give you a ping when done.

**Comment by chrisroadmap** [comment]
Right, have a look at https://doi.org/10.5281/zenodo.5513022 - it might make sense in combination with the AR6 repository.

**Comment by fracamil** [comment]
Thank you very much! It will accelerate the probabilistic runs of FaIR with AR6 set-up and allow me to use efficiently the model :)

**Comment by chrisroadmap** [comment]
Just to say, there will be an AR6-like calibration of FaIR v2 on the way. They are structurally slightly different models so the parameters are not exactly the same, but idea is that they should produce very similar distributions.

**Comment by chrisroadmap** [comment]
This is now in fact done (or at least, in one form) at https://zenodo.org/record/7694879. Closing ticket.
