### ISSUE TITLE
Example Notebook don't load  only says: Sorry, something went wrong. Reload?

### ISSUE THREAD

**Issue by dyrehaugen** [OMS-NetZero/FAIR#79]
**Describe the bug**

**Failing Test**

Please put the code (ideally in the form of a unit
test) which fails below

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

 - OS: [e.g. Windows, Linux, macOS]
 - Python and FaIR version [e.g. Python 3.5]

**Additional context**

**Comment by znicholls** [comment]
Hi, thanks for raising the issue. In my experience this is typically a browser problem which sometimes solves itself with a simple refresh. Sometimes it happens because the notebook is too big. In any case, I’m not sure it’s something we can fix so would close this issue unless @chrisroadmap has other ideas?

**Comment by chrisroadmap** [comment]
I'm going to close this a Zeb has answered above - if the problem persists I would recommend downloading or cloning the repository and accessing the notebook that way.
